version: '3.8'

services:
  frontend:
    build:
      context: .
      target: runner
    container_name: travelfrontend_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    # Uncomment the following lines if you have a .env file you want to use
    # env_file:
    #   - .env
