"use client";

import { DownloadIcon } from "@/components/ui/icons";

interface ItineraryDay {
 day: number;
 title: string;
 description?: string;
}

interface TourItineraryProps {
 days: ItineraryDay[];
 tourTitle?: string;
}

function downloadItinerary(days: ItineraryDay[], tourTitle: string) {
 const rows = days
 .map(
 (item, i) => `
 <div class="day">
 <div class="timeline">
 <div class="dot ${i === 0 || i === days.length - 1 ? "dot-active" : ""}"></div>
 ${i < days.length - 1 ? '<div class="line"></div>' : ""}
 </div>
 <div class="content">
 <p class="day-label">Day ${item.day}</p>
 <p class="day-title">${item.title}</p>
 ${item.description ? `<p class="day-desc">${item.description}</p>` : ""}
 </div>
 </div>`
 )
 .join("");

 const html = `<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8" />
 <title>${tourTitle} — Itinerary</title>
 <style>
 * { margin: 0; padding: 0; box-sizing: border-box; }
 body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #060504; background: #fff; }
 .header { background: #bd8f3a; color: #fff; padding: 18px 32px; }
 .header-label { font-size: 10px; letter-spacing: 2px; text-transform: uppercase; opacity: .8; margin-bottom: 4px; }
 .header-title { font-size: 17px; font-weight: 700; line-height: 1.4; }
 .body { padding: 32px; }
 .divider { border: none; border-top: 1.5px solid #bd8f3a; margin-bottom: 28px; }
 .day { display: flex; gap: 16px; }
 .timeline { display: flex; flex-direction: column; align-items: center; width: 16px; flex-shrink: 0; }
 .dot { width: 12px; height: 12px; border-radius: 50%; background: #d1d5db; margin-top: 3px; flex-shrink: 0; }
 .dot-active { background: #bd8f3a; }
 .line { width: 2px; background: #e5e7eb; flex: 1; min-height: 16px; margin: 4px 0; }
 .content { padding-bottom: 20px; flex: 1; }
 .day-label { font-size: 10px; color: #9ca3af; margin-bottom: 2px; }
 .day-title { font-size: 13px; font-weight: 700; color: #060504; margin-bottom: 4px; }
 .day-desc { font-size: 11px; color: #6b7280; line-height: 1.6; }
 .footer { border-top: 1px solid #e5e7eb; margin: 16px 32px 0; padding: 12px 0; font-size: 9px; color: #9ca3af; }
 @media print { @page { size: A4; margin: 0; } }
 </style>
</head>
<body>
 <div class="header">
 <div class="header-label">Tour Itinerary</div>
 <div class="header-title">${tourTitle}</div>
 </div>
 <div class="body">
 <hr class="divider" />
 ${rows}
 </div>
 <div class="footer">Generated by Viatours</div>
 <script>window.onload = () => { window.print(); window.onafterprint = () => window.close(); }<\/script>
</body>
</html>`;

 const blob = new Blob([html], { type: "text/html" });
 const url = URL.createObjectURL(blob);
 const win = window.open(url, "_blank");
 if (win) win.addEventListener("unload", () => URL.revokeObjectURL(url));
}

export default function TourItinerary({ days, tourTitle = "Tour Itinerary" }: TourItineraryProps) {
 if (!days.length) return null;
 return (
 <section className="pt-8 border-t border-gray-100 dark:border-gray-800">
 <div className="flex items-center justify-between mb-6">
 <h2 className="text-xl font-bold font-raleway text-text-primary">Day-by-day itinerary</h2>
 <button
 onClick={() => downloadItinerary(days, tourTitle)}
 className="flex items-center gap-2 text-sm font-semibold font-open-sans text-primary border border-primary px-4 py-1.5 rounded-full hover:bg-primary/10 transition-colors"
 >
 <DownloadIcon size={14} />
 Download
 </button>
 </div>

 <div className="flex flex-col">
 {days.map((item, i) => {
 const isFirst = i === 0;
 const isLast = i === days.length - 1;
 return (
 <div key={item.day} className="flex gap-4">
 <div className="flex flex-col items-center">
 <div
 className={`w-4 h-4 rounded-full shrink-0 mt-1 z-10 ${
 isFirst || isLast ? "bg-primary" : "bg-gray-300"
 }`}
 />
 {!isLast && <div className="w-0.5 bg-gray-200 flex-1 my-1" />}
 </div>
 <div className="pb-6">
 <p className="text-xs text-gray-700 dark:text-gray-300 font-open-sans mb-0.5">Day {item.day}</p>
 <p className="text-sm font-semibold font-raleway text-text-primary">{item.title}</p>
 {item.description && (
 <p className="text-xs text-gray-700 dark:text-gray-300 font-open-sans mt-1 leading-relaxed">{item.description}</p>
 )}
 </div>
 </div>
 );
 })}
 </div>
 </section>
 );
}
